# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tim Hosgood
email: timhosgood@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thosgood.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  thosgood
twitter_username: tjohnhos
disqus:
  shortname: thosgood
arxiv_username: hosgood_t_1
orcid_id: 0000-0003-4580-0741
matrix_username: thosgood:matrix.org

pagination:
  enabled: true
  debug: false
  sort_reverse: true
  per_page: 6
  permalink: '/page-:num.html'
  limit: 0
  trail: 
    before: 2
    after: 2

excerpt_separator: <!--more-->

minima:
  date_format: "%e %B, %Y"
markdown: kramdown

plugins_dir: ./_plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
jekyll_get:
  - data: github
    json: 'https://api.github.com/users/thosgood/repos'
    cache: false

exclude: [vendor]
